<a href="https://colab.research.google.com/github/HebaSedik/python/blob/master/read_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import *
fname = '1.txt'
dtype1 = dtype([('gender', '|S1'), ('height', 'f8')])
a = loadtxt(fname, dtype=dtype1, skiprows=9, usecols=(1,3))
print(a)

[(b'M', 1.82) (b'M', 1.77) (b'F', 1.68) (b'M', 1.72) (b'F', 1.78)
 (b'F', 1.6 ) (b'M', 1.72) (b'M', 1.83) (b'F', 1.56) (b'F', 1.64)
 (b'M', 1.63) (b'M', 1.67) (b'M', 1.66) (b'F', 1.59) (b'F', 1.7 )
 (b'M', 1.97) (b'F', 1.66) (b'F', 1.63) (b'M', 1.69)]


In [2]:
from numpy import *
a,b,c = loadtxt('0.txt', unpack=True,skiprows=3)
print(a)
print(b)
print(c)

[1890. 1900. 1910. 1920. 1930.]
[26.1 25.9 25.1 24.6 24.3]
[22.  21.9 21.6 21.2 21.3]
